Repository Team-Moiza/MOIZA_SERVER, pull requests merged in 2025-02, with the labels that each got.

#20 merge(#15): service 클래스 이름 변경
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
Labels: Refactor

#19 merge(#14): code domain
  src/main/kotlin/com/example/moiza/domain/code/domain/Code.kt
  src/main/kotlin/com/example/moiza/domain/code/domain/PortfolioCode.kt
  src/main/kotlin/com/example/moiza/domain/code/domain/PortfolioCodeId.kt
  src/main/kotlin/com/example/moiza/domain/code/domain/repository/CodeRepository.kt
  src/main/kotlin/com/example/moiza/domain/code/domain/repository/PortfolioCodeRepository.kt
  src/main/kotlin/com/example/moiza/domain/code/exception/CodeNotFoundException.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/CodeController.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/dto/CreateCodeResponse.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/dto/QueryCodeKeywordResponse.kt
  src/main/kotlin/com/example/moiza/domain/code/service/CreateCodeService.kt
  src/main/kotlin/com/example/moiza/domain/code/service/QueryCodeKeywordService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/PortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/CreatePortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/UpdatePortfolioService.kt
  src/main/kotlin/com/example/moiza/global/error/exception/ErrorCode.kt
  src/test/kotlin/com/example/moiza/MoizaApplicationTests.kt
Labels: ✨ Feature

#22 introduce 속성 변경
  src/main/kotlin/com/example/moiza/domain/user/domain/User.kt
Labels: 🐞 Bug

#24 portfolio list bug수정
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryImpl.kt
Labels: 🐞 Bug

#27 유저 업데이트 API
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepository.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/ChangePublishService.kt
  src/main/kotlin/com/example/moiza/domain/user/domain/User.kt
  src/main/kotlin/com/example/moiza/domain/user/domain/type/Job.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/dto/req/UpdateProfileRequest.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/dto/res/InfoUserResponse.kt
  src/main/kotlin/com/example/moiza/domain/user/service/ProfileService.kt
  src/main/kotlin/com/example/moiza/domain/user/service/UpdateProfileService.kt
Labels: ✨ Feature

#28 merge(#26): 내 이력서 조회
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/PortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/CreatePortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/DeletePortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryMyPortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
Labels: ✨ Feature

#30 merge(#29): 기술 스택 객체로 반환
  src/main/kotlin/com/example/moiza/domain/code/presentation/CodeController.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/dto/CreateCodeResponse.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/dto/QueryCodeResponse.kt
  src/main/kotlin/com/example/moiza/domain/code/service/CreateCodeService.kt
  src/main/kotlin/com/example/moiza/domain/code/service/QueryCodeKeywordService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
Labels: Refactor

#36 like domain, 예외 확장, publish
  src/main/kotlin/com/example/moiza/domain/code/presentation/CodeController.kt
  src/main/kotlin/com/example/moiza/domain/like/domain/Like.kt
  src/main/kotlin/com/example/moiza/domain/like/domain/repository/LikeRepository.kt
  src/main/kotlin/com/example/moiza/domain/like/exception/AlreadyLikeException.kt
  src/main/kotlin/com/example/moiza/domain/like/exception/AlreadyUnLikeException.kt
  src/main/kotlin/com/example/moiza/domain/like/presentation/LikeController.kt
  src/main/kotlin/com/example/moiza/domain/like/presentation/dto/response/LikesResponse.kt
  src/main/kotlin/com/example/moiza/domain/like/service/LikeService.kt
  src/main/kotlin/com/example/moiza/domain/like/service/ListLikesService.kt
  src/main/kotlin/com/example/moiza/domain/like/service/UnLikeService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryImpl.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/ChangePublishService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryMyPortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/UserController.kt
  src/main/kotlin/com/example/moiza/global/config/SecurityConfig.kt
  src/main/kotlin/com/example/moiza/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/example/moiza/global/error/exception/ErrorCode.kt
Labels: ✨ Feature

#32 merge(#31): 포트폴리오 필터링
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryCustom.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryImpl.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/PortfolioFilter.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioListService.kt
Labels: ✨ Feature

#38 fix(portfolio): response null checking 수정
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
Labels: 🐞 Bug

#40 merge(#39): request 수정
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/UpdatePortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/UpdatePortfolioService.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/dto/req/UpdateProfileRequest.kt
  src/main/kotlin/com/example/moiza/domain/user/service/UpdateProfileService.kt
Labels: Refactor

#42 hotfix: user, feat: user drop
  src/main/kotlin/com/example/moiza/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/user/domain/User.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/UserController.kt
  src/main/kotlin/com/example/moiza/domain/user/service/DropUserService.kt
  src/main/kotlin/com/example/moiza/domain/user/service/UpdateProfileService.kt
Labels: 🐞 Bug, ✨ Feature
