Repository Team-Moiza/MOIZA_SERVER, pull requests merged in 2025-03, with the labels that each got.

#46 feat: isLiked
  src/main/kotlin/com/example/moiza/domain/like/presentation/LikeController.kt
  src/main/kotlin/com/example/moiza/domain/like/service/IsLikedService.kt
  src/main/kotlin/com/example/moiza/global/config/SecurityConfig.kt
Labels: ✨ Feature

#48 merge(#47): 상 대회명 추가
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Award.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/PortfolioDtoUtil.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/PortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/UpdatePortfolioService.kt
Labels: Refactor

#52 merge(#51): 프로젝트 코드 추가
  src/main/kotlin/com/example/moiza/domain/code/domain/ProjectCode.kt
  src/main/kotlin/com/example/moiza/domain/code/domain/ProjectCodeId.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Portfolio.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/Project.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/PortfolioDtoUtil.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/PortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/CreatePortfolioService.kt
Labels: Refactor

#50 chore: 프론트 요구사항 반영
  src/main/kotlin/com/example/moiza/domain/code/domain/repository/CodeRepository.kt
  src/main/kotlin/com/example/moiza/domain/code/presentation/CodeController.kt
  src/main/kotlin/com/example/moiza/domain/code/service/GetCodesService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryCustom.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryImpl.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/PortfolioController.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/PortfolioFilter.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/res/QueryPortfolioResponse.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioDetailService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/service/QueryPortfolioListService.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/dto/res/InfoUserResponse.kt
  src/main/kotlin/com/example/moiza/global/config/SecurityConfig.kt
  src/main/kotlin/com/example/moiza/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/example/moiza/global/error/exception/ErrorCode.kt
  src/main/resources/application.yml
Labels: Refactor, ✨ Feature

#54 프로필 사진 추가
  src/main/kotlin/com/example/moiza/domain/auth/service/GoogleAuthService.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/domain/repository/PortfolioRepositoryImpl.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/PortfolioFilter.kt
  src/main/kotlin/com/example/moiza/domain/portfolio/presentation/dto/req/UpdatePortfolioRequest.kt
  src/main/kotlin/com/example/moiza/domain/user/domain/User.kt
  src/main/kotlin/com/example/moiza/domain/user/presentation/UserController.kt
  src/main/kotlin/com/example/moiza/domain/user/service/UpdatePictureService.kt
  src/main/kotlin/com/example/moiza/global/config/properties/NextCloudProperties.kt
  src/main/kotlin/com/example/moiza/global/feign/google/GoogleInformationClient.kt
  src/main/kotlin/com/example/moiza/global/feign/google/dto/res/GoogleInformationResponse.kt
  src/main/kotlin/com/example/moiza/global/feign/nextcloud/NextcloudShareClient.kt
  src/main/kotlin/com/example/moiza/global/feign/nextcloud/NextcloudUploadClient.kt
  src/main/kotlin/com/example/moiza/global/feign/nextcloud/dto/res/ShareUrlResponse.kt
  src/main/kotlin/com/example/moiza/global/utils/nextcloud/NextCloudService.kt
  src/main/resources/application.yml
Labels: 🐞 Bug, ✨ Feature
